#El bloque except: permite manejar errores en caso de que estos ocurran.


try: # se utiliza la excepcion, se ejecuta el bloque de prueba
    print(var) #se imprime la variable

except: #se salta la ejecucion en caso de que curra
    print("No hay nada ")

print("\n")

#El bloque try:permite probar un bloque de c√≥digo en busca de errores.

var = "Afirmativo"
try: # se utiliza la excepcion, se ejecuta el bloque de prueba
    print(var) #se imprime la variable

except: #se salta la ejecucion en caso de que curra
    print("No hay nada ")
